creditapp/urls.py
from creditapp.views import *

app_name="creditapp"

urlpatterns=[
    #path('crd/',CardView.as_view(),name="cards"),

    path('cards/', CreditList.as_view(), name="credit_list"),

    path('cards/add/', AddCard.as_view(), name="add_card"),

    path('cards/<int:pk>/edit/', EditCard.as_view(), name="edit_card"),

    path('cards/<int:pk>/delete/', DeleteCard.as_view(), name="delete_card"),

    path('login/', LoginController.as_view(), name="login"),

    path('logout/', logout_user, name="logout"),
        ]

creditproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('creditapp/', include('creditapp.urls')),
]

creditapp/models.py
from django.db import models
from django.contrib.auth.models import *
# Create your models here.
from django.db import models
import datetime
from django.contrib.auth.models import *
# Create your models here.

class Card(models.Model):
    friendly_name = models.CharField(max_length=32)
    name_on_card = models.CharField(max_length=128)
    expiry_date=models.DateField(null=True,blank=True)
    typec = models.CharField(max_length=64)
    cvv=models.CharField(max_length=3)
    card_number=models.CharField(max_length=20)

    user=models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.name_on_card

creditapp/forms/card.py
from creditapp.models import *
from django import forms

class Addcard(forms.ModelForm):
    class Meta:
        model=Card
        exclude = ['id','user']
        widgets={
            ' friendly_name':forms.TextInput(attrs={'class':'form-control','placeholder':'friendly name'}),
            'name_on_card':forms.TextInput(attrs={'class':'form-control','placeholder':'card name'}),
            'expiry_date':forms.DateInput(attrs={'class':'form-control','placeholder':'expirydate'}),
            'typec':forms.TextInput(attrs={'class':'form-control','placeholder':'type'}),
            'cvv': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'cvv'}),
            'card_number': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'cardnumber'})
        }



class Loginform(forms.Form):
    username = forms.CharField(
        max_length=75,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'enter first name'})
    )
    password = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'enter first name'})
    )

creditapp/views.py
from django.views import View

from creditapp.models import *
from django.http import *
from django.shortcuts import *

from django.shortcuts import render
from django.views.generic import *
from django.contrib.auth.mixins import *
from creditapp.forms import *
from django.urls import *

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import *
from django.contrib import messages
from django.contrib.auth.models import *
from django.contrib.auth import *
app_name="creditapp"

class CreditList(LoginRequiredMixin, ListView):
    login_url = 'creditapp:login'
    model = Card
    context_object_name = 'jails'
    template_name = 'creditapp/credit_list.html'

    def get_context_data(self, object_list=None, **kwargs):
        context = super(CreditList, self).get_context_data(**kwargs)
        context.update(
            {
                'jails': Card.objects.filter(user__username = self.request.user.username)
            }
        )
        return context


class AddCard(LoginRequiredMixin, CreateView):
    login_url = 'creditapp:login'
    model = Card
    form_class = Addcard
    success_url = reverse_lazy('creditapp:credit_list')

    def get_context_data(self, **kwargs):
        context = super(AddCard, self).get_context_data(**kwargs)
        context.update({
            'form': context.get('form'),
        })
        return context
    def post(self, request, *args, **kwargs):
        user = User.objects.get(username = request.user.username)
        user = get_object_or_404(User, pk=user.id)
        form = Addcard(request.POST)

        if form.is_valid():
            card = form.save(commit=False)
            card.user = user
            card.save()

            return redirect('creditapp:credit_list')


class DeleteCard(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    login_url = 'creditapp:login'
    model = Card
    template_name = 'creditapp/delete.html'
    success_url = reverse_lazy('creditapp:credit_list')

    def has_permission(self):
        res = Card.objects.filter(user__username = self.request.user.username, id = self.kwargs['pk'])
        if len(res)!=0:
            return True
        else:
            self.raise_exception=True
            return False


class EditCard(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    login_url = 'creditapp:login'
    model = Card
    form_class = Addcard
    success_url = reverse_lazy('creditapp:credit_list')

    def has_permission(self):
        res = Card.objects.filter(user__username = self.request.user.username, id = self.kwargs['pk'])
        if len(res)!=0:
            return True
        else:
            self.raise_exception=True
            return False


    def get_object(self, queryset=None):
        return get_object_or_404(Card, **{'pk': self.kwargs.get('pk')})

    def get_context_data(self, **kwargs):
        context = super(EditCard, self).get_context_data(**kwargs)
        return context


class LoginController(View):
    def get(self,request,*args,**kargs):
        login =  Loginform()
        return render(
            request,
            template_name="creditapp/login.html",
            context={'form':login,'title':'Login Form'}
        )

    def post(self, request, *args, **kwargs):
        form = Loginform(request.POST)
        if form.is_valid():
            user = authenticate(
                request,
                username=form.cleaned_data['username'],
                password = form.cleaned_data['password'],
            )
            if user is not None:
                login(request,user)
                return redirect('creditapp:credit_list')
            else:
                messages.error(request,"Invalid Credentials")
                return redirect('creditapp:login')

def logout_user(request):
    logout(request)
    return redirect('creditapp:login')

creditapp/templates/creditapp/card_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="container">
    <div class="col-xs-6 col-xs-offset-3">
        <form method="POST">
            {% csrf_token %}
            <fieldset>
                <legend>Add College</legend>
                <div class="form-group">
                    <label for="{{ form.friendly_name.id_for_label }}">Enter friendlyName</label>
                    {{ form.friendly_name }}</div>
                <div class="from-group">
                    <label for="{{ form.name_on_card.id_for_label}}">Enter name</label>
                    {{ form.name_on_card }}
                </div>
                <div class="from-group">
                    <label for="{{ form.expiry_date.id_for_label}}">Enter date</label>
                    {{ form.expiry_date}}
                </div>
                 <div class="from-group">
                    <label for="{{ form.typec.id_for_label}}">Enter type</label>
                    {{ form.typec}}
                </div>

                 <div class="from-group">
                    <label for="{{ form.cvv.id_for_label}}">Enter cvv</label>
                    {{ form.cvv}}
                </div>

                 <div class="from-group">
                    <label for="{{ form.card_number.id_for_label}}">Enter card number</label>
                    {{ form.card_number}}
                </div>
                <input type="submit" value="submit">
            </fieldset>
        </form>
    </div>
</div>
</body>
</html>

creditapp/templates/creditapp/credit_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">


     <link href="css/bootstrap.min.css"rel="stylesheet"media="screen">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>college</title>
    <script>
</script>
</head>
<body>

    <form>
        <fieldset>

      <center> <h3>Cards</h3></center>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<button><a href="{% url 'creditapp:logout'%}">Log Out</a></button>
            <br>
            <br>
            <div class="form-group">
                <button><a href="{% url 'creditapp:add_card'%}">Add Card</a></button>
            </div>

            <br>
            <br>

    <table class="table">
       <tr>
  <th>friendly_name</th>
    <th>card_on_name</th>
    <th>expiry_date</th>
    <th>typec</th>
     <th>cvv</th>
     <th>card_number</th>
           <th>Action</th>
        </tr>
{% for i in jails %}
<tr>
  <td>{{i.friendly_name}}</td>
    <td>{{i.name_on_card}}</td>
    <td>{{i.expiry_date}}</td>
    <td>{{i.typec}}</td>
     <td>{{i.cvv}}</td>
     <td>{{i.card_number}}</td>

      <td>
                <a href="{% url 'creditapp:edit_card' i.id %}">Edit</a> |
                <a href="{% url 'creditapp:delete_card' i.id %}">Delete</a>
            </td>

</tr>
        {% endfor %}
    </table>
             </fieldset>
    </form>

</body>
</html>

creditapp/templates/creditapp/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete</title>
</head>
<body>
<div class="container">
        <h1><b>Delete Card</b></h1>
        <form method="post">{% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}"?</p>
            <input type="submit" value="Confirm" />
        </form>
    </div>
</body>
</body>
</html>

creditapp/templates/creditapp/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
<div class="container">
    <div class="col-xs-6 col-xs-offset-3">
        <form method="POST">
            {% csrf_token %}
            <fieldset>
                <legend>Log in</legend>
                <div class="form-group">
                    <label for="{{ form.user_name.id_for_label}}">Enter Username</label>
                    {{ form.username}}
                </div>
                 <div class="forlm-group">
                    <label for="{{ form.password.id_for_label}}">Enter Password</label>
                    {{ form.password}}
                </div>
                <input type="submit" value="Login">
            </fieldset>
        </form>
    </div>
</div>
</body>
</html>